GET http://localhost:3003/usuarios
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mywicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMxMTc0ODk1LCJleHAiOjE3MzEyNjEyOTV9.0Pz65X5mhVLQobWetP0mkVPvHanaP1qxJv_Q3rswB4Y
###
POST http://localhost:3003/usuarios
Content-Type: application/json

{
   "email": "admin@teste.com",
   "password": "123",
   "role": "admin"
}

###
POST http://localhost:3003/usuarios/login
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMwNzY4MTEwLCJleHAiOjE3MzA3NzUzMTB9.0Piw-v2zXwfT_NdSFpUoHSmk0Uiqsnu7jC3fsLrv0zE

{
   "email": "admin@teste.com",
   "password": "123"
}
###
PUT http://localhost:3003/usuarios/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMwNzY4MTEwLCJleHAiOjE3MzA3NzUzMTB9.0Piw-v2zXwfT_NdSFpUoHSmk0Uiqsnu7jC3fsLrv0zE

{
   "email": "entregador@teste.com",
   "password": "12345",
   "role": "entregador"
}
###
DELETE http://localhost:3003/usuarios/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzMwNzY4MTEwLCJleHAiOjE3MzA3NzUzMTB9.0Piw-v2zXwfT_NdSFpUoHSmk0Uiqsnu7jC3fsLrv0zE